### PR TITLE
Add fakeroot support for Arch packaging in stable branch

### PR DESCRIPTION
**Pull request by Shadowigor**
As discussed in #60.

### CODE REVIEW

**Comment by Shadowigor** [comment]
I've uploaded the package to the AUR now. You can find it [here](https://aur.archlinux.org/packages/osync/).

**Comment by deajan** [comment]
Just a question, why is it named "v1.00.r219.f70d8cd-1" as osync current stable is v1.1.2 ?

**Comment by Shadowigor** [comment]
It's extracted from '[git describe](https://git-scm.com/docs/git-describe)'

> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit.

It's the suggested way to dynamically generate a version string. But you are right, it seems to ignore the latest version tags. I fixed it as suggested [here](http://stackoverflow.com/q/4154485). The version is v1.1.2.r9.b8ff024 now.

**Comment by deajan** [comment]
Perfect :) Thanks

**Pull request merged**
