### PR TITLE
Add OpenRC support, fixed daemon script

### LINKED ISSUE #140: OpenRC support
It'd be really great to have support for OpenRC init scripts for osync.

### PR DESCRIPTION
**Pull request by kozross**
This fixes #140. All credit goes to Brian (aka grknight), not me, although I did document and test this.

### CODE REVIEW

**Comment by deajan** [comment]
Thank you for your PR.
There are a couple of adjustments to do before I can merge:

- the README.md commit states that osync has been tested on Gentoo. I cannot leave that statement as is as I didn't run the test script, which I do run for every single release on every stated Gentoo. I'll modify that statement to "some users have successfully used on Gentoo" or so.

- I need to modify the openrc script (program name should not be the init script here, neither the author name, which are totally fine when set as comments and not variables)

- I need to add open-rc detection to install.sh. Can you give me a hint what binary to test for ? The one in the shebang ?

Again, thank you for the time you took bringing this PR in.

**Comment by deajan** [comment]
Totally forgot about this one, just coded the installer bits here https://github.com/deajan/osync/commit/de57e372173931587e1cb3f1d264dd9fee4f3c01
Will integrate this PR in the week.
Would you mind testing afterwards ?

**Comment by kozross** [comment]
Certainly, once it's merged.

**Comment by deajan** [comment]
Merged... and thanks a lot.
Could you test the installer script see if it works for you ?

**Pull request merged**
