### PR TITLE
Check if master and slave dirs are not same.

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Comment by deajan** [comment]
Had to add check if slave dir is remote to your PR.

**Comment by onovy** [comment]
thanks for fix

**Comment by konpa** [comment]
This pull gives an error message on mac:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
TIME: 0 - Master directory [...] can't be the same as slave directory.
```

I had to remove those lines in order to get it working. 

PS: nice work by the way :) thx

**Comment by deajan** [comment]
Thanks for reporting.
Guess you're using MacOs X ?
I plan to use the following code snippet from http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac to simuate readlink -f instead.
```
real_path () {
  OIFS=$IFS
  IFS='/'
  for I in $1
  do
    # Resolve relative path punctuation.
    if [ "$I" = "." ] || [ -z "$I" ]
      then continue
    elif [ "$I" = ".." ]
      then FOO="${FOO%%/${FOO##*/}}"
           continue
      else FOO="${FOO}/${I}"
    fi

    ## Resolve symbolic links
    if [ -h "$FOO" ]
    then
    IFS=$OIFS
    set `ls -l "$FOO"`
    while shift ;
    do
      if [ "$1" = "->" ]
        then FOO=$2
             shift $#
             break
      fi
    done
    IFS='/'
    fi
  done
  IFS=$OIFS
  echo "$FOO"
}```

I just have to check BSD compat too.

**Comment by deajan** [comment]
Updated with some portable shell code.
Can you confirm it works ?

**Pull request merged**
