### PR TITLE
Initial changes to support SSH Multiplexing

### PR DESCRIPTION
**Pull request by bmorgenthaler**
These are changed to enable SSH Multiplexing for all subsequent connections after the first.

Added the SSH_CONTROLMASTER option, which when set has ssh connections either setup a ControlMaster socket or utilize the existing one.

### CODE REVIEW

**Comment by deajan** [comment]
Your code seems good so far, but I don't see where you enable that.
There is neither an option in sync.conf, nor a runtime option like --sshcontrolmaster.

Do you run this with a modded config file ?

**Comment by bmorgenthaler** [comment]
I didn't modify the example config file, I missed that with this commit.  I enabled it like REMOTE_HOST_PING and SSH_IGNORE_KNOWN_HOSTS by setting it to TRUE on the command line.

`SSH_CONTROLMASTER=true REMOTE_HOST_PING=false /dev/github/bmorgenthaler/osync/dev/bootstrap.sh program=osync.sh --target=ssh://remoteserver/share --initiator=/local/share`

**Comment by deajan** [comment]
Okay I see, I'll review your code in detail later, and if it happens to work without breaking anything else (which I suspect from the first read), I'll add the necessary bits for a commandline switch and the config file.
I'll also make some quick with and without benchmarks.

In the meantime, thanks for your work.

**Comment by deajan** [comment]
Works for me.
I will make some modifications so multiple concurrent osync instances won't use the same control master too.

**Comment by deajan** [comment]
Added some work to make the SSH_CONTROLMASTER / --ssh-controlmaster a first class citizen in osync.
For now, I still have some integration tests that fail.

**Comment by deajan** [comment]
Integration tests now run with --ssh-controlmaster option.
Feature seems complete.
Made a notice for layer documentation.

Afin, thanks for your PR.

**Comment by deajan** [comment]
If you use SSH_CONTROLMASTER option with osync, I'd suggets to update to current master as previous versions leave SSH processes open after closing the controlmaster stream.

**Pull request merged**
