### PR TITLE
Transform tested platforms list into a table

### PR DESCRIPTION
**Pull request by vitorhcl**
This makes the list more readable

### CODE REVIEW

**Comment by deajan** [comment]
Thanks for your time.
Please remove the method column and put "via termux" in the version column of android, that will be much clearer.

**Comment by vitorhcl** [comment]
> Thanks for your time. Please remove the method column and put "via termux" in the version column of android, that will be much clearer.

Do you think that both Android and Windows should use the version column for the method? IMO a separate column is much more clearer, we can even rename it to "Notes" and put things like OpenRC and InitV. After all, you decide it.

**Comment by deajan** [comment]
I don't feel like a Method / notes table makes things easier.
Also, systemd, initv and openrc don't have their place in the list.
How about you just remove them completely, and just add two footnotes for android and windows ?

**Comment by vitorhcl** [comment]
> I don't feel like a Method / notes table makes things easier.
> Also, systemd, initv and openrc don't have their place in the list.
> How about you just remove them completely, and just add two footnotes for android and windows ?

I thought of 2 options:
1. Remove the 2 platforms completely from the table and the methods/notes column and add a note later like the Gentoo + OpenRC mention.
2. Only remove the methods/notes column and add "*" and "**" and footnotes below the table

What approach do you think is best for me to take?

**Comment by deajan** [comment]
Option 2 sounds good to me ;)
Thank you for your time investment.

**Comment by vitorhcl** [comment]
No problem! So I'm gonna do the 2nd option.

**Comment by deajan** [comment]
Thank you Vitor, appreciating.

**Pull request merged**
