### PR TITLE
Enable installation with different root for (Arch) packaging

### PR DESCRIPTION
**Pull request by Shadowigor**
I would like to make a package of osync for Arch Linux and put it into the AUR, but for that I need to be able to install osync in a different root (fakeroot). This patch would allow me to do that so I could package it with your current upstream version.

### CODE REVIEW

**Comment by deajan** [comment]
Thanks for your commit.
Actually install.sh is autogenerated from dev/common_install.sh
Would you mind to rebase your PR to this file so I don't have to manually merge it and you keep the authorship ?

Also, please commit the spec file to spec/ so your work can be kept.

**Comment by Shadowigor** [comment]
I moved my changes to dev/common_install.sh, but I don't really know what you mean with the spec file. I also suppose, that dev/merge.sh is the script that auto-generates everything, but I was unable run it because it expects something to be in /home/git.

Another thing, the master branch seems to be the development branch and v1.1-maint the more or less stable branch for version 1.1, right? If you had another branch that points to the current stable version, it would simplify maintaining the future package at lot, because I wouldn't have to update the package that often and it would always be a stable release.

**Comment by deajan** [comment]
I don't really know how it works with arch, but in redhat you get a SPEC file to built the packages via rpmbuild. I gues there's something similar for arch ?
I've forgotten to update the dev/merge.sh script which shares code with other projects. Done, should build now !
Yes, master is dev branch and v1.1-maint is the actual stable branch until v1.2 becomes stable.
I'm not sure whether I can have a stable branch that points to another branch. Maybe renaming v1.1-maint to stable could be a solution.

**Comment by Shadowigor** [comment]
Ah, ok, I didn't know that. Arch has a PKGBUILD file for this, but it will be uploaded to the AUR servers anyway, so I think there is no point in adding it to this repo too.

Thanks, yes, dev/merge.sh works now. 

If you don't need to be able to still maintain v1.1 after v1.2 became stable, I think it would really be simpler if the stable branch would be called something like 'stable'. Everything else could get quite complicated or confusing. And you can still add a tag for the final version of v1.1 if you want.

**Comment by deajan** [comment]
I do think that it is useful to have the PKGBUILD file uploaded here, as it may be updated for dev versions. When stable becomes old-stable and dev becomes stable, you don't have to try to see what changed, because the PKGBUILD file will already be ready to be uploaded to the AUR server.

**Comment by deajan** [comment]
I've reviewed your PR and the install code looks fine.
Just please don't modify any other file than common_install.sh as I am getting a huge PR with a lot of code modifications which aren't supposed to come with your PR.
Once this is done, I'll be happy to merge.

**Comment by Shadowigor** [comment]
Normally, you won't have to edit the PKGBUILD manually, you just have to run a script to update the version. You could of course maintain a PKGBUILD for the dev version, but as you're not running Arch it would be untested and for me to upload every new PKGBUILD for every new version seems quite redundant, as it is on the AUR git anyway. Here is the PKGBUILD I currently have as an example anyway:

```
# Maintainer: Shadowigor <shadowigorr at gmail dot com>
pkgname="osync"
pkgver=v1.00.r219.f70d8cd
pkgrel=1
pkgdesc="A two way filesync script"
arch=("any")
url="https://github.com/deajan/osync"
license=('custom')
depends=('rsync')
makedepends=('git')
provides=("$pkgname")
source=('git+https://github.com/deajan/osync.git#branch=stable')
md5sums=('SKIP')

pkgver()
{
    cd "$srcdir/$pkgname"
    printf "%s" "$(git describe --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

prepare()
{
    cd "$pkgname"
    find . -type f -exec sed -i "s:/usr/local:/usr:g" {} ";"
    find . -type f -exec sed -i "s:/lib:/usr/lib:g" {} ";"
}

package()
{
    cd "$pkgname"
    echo n | FAKEROOT="$pkgdir" bash ./install.sh > /dev/null
}
```

**Comment by Shadowigor** [comment]
About the PR, I'll look into it, but that's probably because your master is constantly updating with changes I don't have yet. I didn't touch the other files.

**Comment by Shadowigor** [comment]
Ok, I updated it. As long as you don't push more commits to your master, only dev/common_install.sh and the (autogenerated) install.sh should have changes.

**Comment by deajan** [comment]
Perfect. I'll add the pkgbuild file to current dev.

**Comment by deajan** [comment]
As for the branch names, I can't rename v1.1-maint branch because it's referenced. I've forked it to a new branch called stable which I'll simply update with v1.1-maint branch so the package building works.

**Comment by Shadowigor** [comment]
Great! But I would of course also need the PR in 'stable' for the packaging ^^

**Comment by deajan** [comment]
Well... Can you open a PR for stable or shall I just...copy & paste (you'll loose authorship) ?

**Comment by Shadowigor** [comment]
I created one (#62).

**Comment by deajan** [comment]
Merged. Thanks again.

**Comment by deajan** [comment]
Quick question, I've updated osync stable release.
What's the procedure to get the arch package updated ?

**Comment by Shadowigor** [comment]
My plan was to check for updates from time to time and updated it, but if you would like to update it right after an update, you can of course do so. I just realized, that the tools needed to do so are just bash scripts, so you should be able to run them as well. I can add the tools and an update script to the repo if you like.

**Comment by deajan** [comment]
Why not. I'm not releasing one version every day :)
At least I will try to maintain a recent package.

**Comment by Shadowigor** [comment]
Great, I've made a PR (#70).

**Comment by deajan** [comment]
I've reviewed your PR, but there is more than just bash scripts.
I don't have an Arch install, so I don't have pacman to build the packages using the scripts.
I more thought of a build system like fedora / opensuse where the server builds the packages.
I've seen that I can install pacman on my current Fedora, I'll have a test run these days.
I'll come back to you once I've tested. Thanks.

**Comment by Shadowigor** [comment]
I don't really see why you would need pacman to update the version, you don't need to install, not even build the package to update the version. mksrcinfo and my script should be quite pure bash. It just pulls the source and gets the current version out of git.

**Pull request merged**
