### PR TITLE
Add script to automatically update the PKGBUILD

### PR DESCRIPTION
**Pull request by Shadowigor**
As discussed in #60, I've added everything necessary to update the Arch package. All you have to do is to run the `update-osync-pkg.sh` script. It will automatically pull the latest PKGBUILD from the AUR servers (which is why I deleted the PKGBUILD here), updates it with the latest version, and pushes everything back to the AUR servers. If you create an account for the AUR [here](https://aur.archlinux.org/) and tell me your username, I'll add you as a co-maintainer, which will grant you access to push updates. I didn't update the package to the latest version yet, so you can try it and we'll see if it works for you.

### CODE REVIEW

**Comment by Shadowigor** [comment]
Any updates?

**Comment by deajan** [comment]
Sorry, it's been about three weeks that I could not work on osync and there are two more weeks comming before I can resume work on this project. Please be patient.

**Comment by deajan** [comment]
Hello, sorry for being late for the party, it's really been two months :(
I've created an account on aur.archlinux.org, username: deajan
Can you add me as co-maintainer so I get to check everything and merge it ?

**Comment by Shadowigor** [comment]
No problem. I've added you as a co-maintainer, you should be able to push to the repo now.

**Comment by deajan** [comment]
I've merged your (btw really nice) auto update script.
Made a small ajustment being the pkgver variable automatically updated from current osync version.
Is there any reason why the pkgver from your PKGBUILD file had the suffix ".r9.b8ff024" ?
If so, please tell me before I commit the same to the stable branch.

**Comment by Shadowigor** [comment]
Your adjustment is fine, I just used the recommended way of getting the version by getting it from git directly and that version string is a combination of the current version tag and the current commit hash. Your solution is probably cleaner, I just didn't knew how to reliably extract the exact version from osync.

**Comment by deajan** [comment]
Just added to v1.1-maint but I'm still having a problem.
In mksrcinfo line 38, there's ```declare -n```.

My bash version (CentOS 7 bash 4.2) does not support -n switch.
What shell did you use, and maybe could you tell me what -n does so I can find a workaround ?

**Comment by Shadowigor** [comment]
http://wiki.bash-hackers.org/commands/builtin/declare:

_"[-+]n	make NAME a reference to the variable named by its value. Introduced in Bash 4.3-alpha"_

Seems like it was introduced in bash 4.3. Shouldn't be too hard to work around though, because as I see it, the reference it creates is only used once.

**Comment by deajan** [comment]
I've made a small mod to get that script compatible with my older bash version.
Think we're all good now ! I'll have that script running on new stable releases from now.

Big thanks for your work.

**Comment by Shadowigor** [comment]
And thank you for keeping it up to date. I've just updated my osync version through the AUR and so far it looks like everything works like a charm.

**Pull request merged**
